// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/core.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoipCore_RouteCall_FullMethodName = "/voipcore.VoipCore/RouteCall"
)

// VoipCoreClient is the client API for VoipCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoipCoreClient interface {
	RouteCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
}

type voipCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewVoipCoreClient(cc grpc.ClientConnInterface) VoipCoreClient {
	return &voipCoreClient{cc}
}

func (c *voipCoreClient) RouteCall(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, VoipCore_RouteCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoipCoreServer is the server API for VoipCore service.
// All implementations must embed UnimplementedVoipCoreServer
// for forward compatibility.
type VoipCoreServer interface {
	RouteCall(context.Context, *CallRequest) (*CallResponse, error)
	mustEmbedUnimplementedVoipCoreServer()
}

// UnimplementedVoipCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoipCoreServer struct{}

func (UnimplementedVoipCoreServer) RouteCall(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RouteCall not implemented")
}
func (UnimplementedVoipCoreServer) mustEmbedUnimplementedVoipCoreServer() {}
func (UnimplementedVoipCoreServer) testEmbeddedByValue()                  {}

// UnsafeVoipCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoipCoreServer will
// result in compilation errors.
type UnsafeVoipCoreServer interface {
	mustEmbedUnimplementedVoipCoreServer()
}

func RegisterVoipCoreServer(s grpc.ServiceRegistrar, srv VoipCoreServer) {
	// If the following call pancis, it indicates UnimplementedVoipCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoipCore_ServiceDesc, srv)
}

func _VoipCore_RouteCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoipCoreServer).RouteCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VoipCore_RouteCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoipCoreServer).RouteCall(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VoipCore_ServiceDesc is the grpc.ServiceDesc for VoipCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoipCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voipcore.VoipCore",
	HandlerType: (*VoipCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteCall",
			Handler:    _VoipCore_RouteCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core.proto",
}
