// proto/core/core.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: proto/core/core.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallResponse_Status int32

const (
	CallResponse_OK     CallResponse_Status = 0
	CallResponse_FAILED CallResponse_Status = 1
)

// Enum value maps for CallResponse_Status.
var (
	CallResponse_Status_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	CallResponse_Status_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x CallResponse_Status) Enum() *CallResponse_Status {
	p := new(CallResponse_Status)
	*p = x
	return p
}

func (x CallResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_core_core_proto_enumTypes[0].Descriptor()
}

func (CallResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_core_core_proto_enumTypes[0]
}

func (x CallResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallResponse_Status.Descriptor instead.
func (CallResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{1, 0}
}

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_proto_core_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CallRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CallResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=voipcore.CallResponse_Status" json:"status,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RtpPort       uint32                 `protobuf:"varint,3,opt,name=rtp_port,json=rtpPort,proto3" json:"rtp_port,omitempty"` // <-- YENİ ALAN EKLENDİ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_proto_core_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_core_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetStatus() CallResponse_Status {
	if x != nil {
		return x.Status
	}
	return CallResponse_OK
}

func (x *CallResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CallResponse) GetRtpPort() uint32 {
	if x != nil {
		return x.RtpPort
	}
	return 0
}

var File_proto_core_core_proto protoreflect.FileDescriptor

const file_proto_core_core_proto_rawDesc = "" +
	"\n" +
	"\x15proto/core/core.proto\x12\bvoipcore\"1\n" +
	"\vCallRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\x9d\x01\n" +
	"\fCallResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.voipcore.CallResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\brtp_port\x18\x03 \x01(\rR\artpPort\"\x1c\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\n" +
	"\n" +
	"\x06FAILED\x10\x012F\n" +
	"\bVoipCore\x12:\n" +
	"\tRouteCall\x12\x15.voipcore.CallRequest\x1a\x16.voipcore.CallResponseB%Z#github.com/Centiric/core/proto/coreb\x06proto3"

var (
	file_proto_core_core_proto_rawDescOnce sync.Once
	file_proto_core_core_proto_rawDescData []byte
)

func file_proto_core_core_proto_rawDescGZIP() []byte {
	file_proto_core_core_proto_rawDescOnce.Do(func() {
		file_proto_core_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_core_proto_rawDesc), len(file_proto_core_core_proto_rawDesc)))
	})
	return file_proto_core_core_proto_rawDescData
}

var file_proto_core_core_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_core_core_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_core_core_proto_goTypes = []any{
	(CallResponse_Status)(0), // 0: voipcore.CallResponse.Status
	(*CallRequest)(nil),      // 1: voipcore.CallRequest
	(*CallResponse)(nil),     // 2: voipcore.CallResponse
}
var file_proto_core_core_proto_depIdxs = []int32{
	0, // 0: voipcore.CallResponse.status:type_name -> voipcore.CallResponse.Status
	1, // 1: voipcore.VoipCore.RouteCall:input_type -> voipcore.CallRequest
	2, // 2: voipcore.VoipCore.RouteCall:output_type -> voipcore.CallResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_core_core_proto_init() }
func file_proto_core_core_proto_init() {
	if File_proto_core_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_core_proto_rawDesc), len(file_proto_core_core_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_core_proto_goTypes,
		DependencyIndexes: file_proto_core_core_proto_depIdxs,
		EnumInfos:         file_proto_core_core_proto_enumTypes,
		MessageInfos:      file_proto_core_core_proto_msgTypes,
	}.Build()
	File_proto_core_core_proto = out.File
	file_proto_core_core_proto_goTypes = nil
	file_proto_core_core_proto_depIdxs = nil
}
