// media/proto/media.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc1
// source: proto/media/media.proto

// !!! RUST'A ÖZEL BU SATIRI KALDIRDIK VEYA YORUM SATIRI YAPTIK !!!
// option rust_package = "media";

package media

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaManager_AllocatePort_FullMethodName = "/media.MediaManager/AllocatePort"
)

// MediaManagerClient is the client API for MediaManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Media servisi
type MediaManagerClient interface {
	AllocatePort(ctx context.Context, in *AllocatePortRequest, opts ...grpc.CallOption) (*AllocatePortResponse, error)
}

type mediaManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaManagerClient(cc grpc.ClientConnInterface) MediaManagerClient {
	return &mediaManagerClient{cc}
}

func (c *mediaManagerClient) AllocatePort(ctx context.Context, in *AllocatePortRequest, opts ...grpc.CallOption) (*AllocatePortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocatePortResponse)
	err := c.cc.Invoke(ctx, MediaManager_AllocatePort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MediaManagerServer is the server API for MediaManager service.
// All implementations must embed UnimplementedMediaManagerServer
// for forward compatibility.
//
// Media servisi
type MediaManagerServer interface {
	AllocatePort(context.Context, *AllocatePortRequest) (*AllocatePortResponse, error)
	mustEmbedUnimplementedMediaManagerServer()
}

// UnimplementedMediaManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaManagerServer struct{}

func (UnimplementedMediaManagerServer) AllocatePort(context.Context, *AllocatePortRequest) (*AllocatePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocatePort not implemented")
}
func (UnimplementedMediaManagerServer) mustEmbedUnimplementedMediaManagerServer() {}
func (UnimplementedMediaManagerServer) testEmbeddedByValue()                      {}

// UnsafeMediaManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaManagerServer will
// result in compilation errors.
type UnsafeMediaManagerServer interface {
	mustEmbedUnimplementedMediaManagerServer()
}

func RegisterMediaManagerServer(s grpc.ServiceRegistrar, srv MediaManagerServer) {
	// If the following call pancis, it indicates UnimplementedMediaManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaManager_ServiceDesc, srv)
}

func _MediaManager_AllocatePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocatePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaManagerServer).AllocatePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaManager_AllocatePort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaManagerServer).AllocatePort(ctx, req.(*AllocatePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MediaManager_ServiceDesc is the grpc.ServiceDesc for MediaManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "media.MediaManager",
	HandlerType: (*MediaManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocatePort",
			Handler:    _MediaManager_AllocatePort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/media/media.proto",
}
